/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin/login'
import { Route as SuperAdminProtectedRouteRouteImport } from './routes/super-admin/_protected/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as SuperAdminProtectedUsersRouteImport } from './routes/super-admin/_protected/users'
import { Route as SuperAdminProtectedTrialsRouteImport } from './routes/super-admin/_protected/trials'
import { Route as SuperAdminProtectedSubscriptionsRouteImport } from './routes/super-admin/_protected/subscriptions'
import { Route as SuperAdminProtectedSettingsRouteImport } from './routes/super-admin/_protected/settings'
import { Route as SuperAdminProtectedReportsRouteImport } from './routes/super-admin/_protected/reports'
import { Route as SuperAdminProtectedPlansRouteImport } from './routes/super-admin/_protected/plans'
import { Route as SuperAdminProtectedPaymentsRouteImport } from './routes/super-admin/_protected/payments'
import { Route as SuperAdminProtectedMaintenanceRouteImport } from './routes/super-admin/_protected/maintenance'
import { Route as SuperAdminProtectedDashboardRouteImport } from './routes/super-admin/_protected/dashboard'
import { Route as SuperAdminProtectedCompaniesRouteImport } from './routes/super-admin/_protected/companies'
import { Route as SuperAdminProtectedBackupRouteImport } from './routes/super-admin/_protected/backup'
import { Route as SuperAdminProtectedAuditRouteImport } from './routes/super-admin/_protected/audit'
import { Route as AuthenticatedAppWarehousesRouteImport } from './routes/_authenticated/app/warehouses'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app/team'
import { Route as AuthenticatedAppSuppliersRouteImport } from './routes/_authenticated/app/suppliers'
import { Route as AuthenticatedAppStockRouteImport } from './routes/_authenticated/app/stock'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppSalesRouteImport } from './routes/_authenticated/app/sales'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app/reports'
import { Route as AuthenticatedAppQuotationsRouteImport } from './routes/_authenticated/app/quotations'
import { Route as AuthenticatedAppPurchasesRouteImport } from './routes/_authenticated/app/purchases'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app/products'
import { Route as AuthenticatedAppPosRouteImport } from './routes/_authenticated/app/pos'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app/notifications'
import { Route as AuthenticatedAppInvoicesRouteImport } from './routes/_authenticated/app/invoices'
import { Route as AuthenticatedAppExpensesRouteImport } from './routes/_authenticated/app/expenses'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app/customers'
import { Route as AuthenticatedAppCompaniesRouteImport } from './routes/_authenticated/app/companies'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app/audit'
import { Route as AuthenticatedAppAccountingRouteImport } from './routes/_authenticated/app/accounting'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminProtectedRouteRoute =
  SuperAdminProtectedRouteRouteImport.update({
    id: '/super-admin/_protected',
    path: '/super-admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SuperAdminProtectedUsersRoute =
  SuperAdminProtectedUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedTrialsRoute =
  SuperAdminProtectedTrialsRouteImport.update({
    id: '/trials',
    path: '/trials',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedSubscriptionsRoute =
  SuperAdminProtectedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedSettingsRoute =
  SuperAdminProtectedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedReportsRoute =
  SuperAdminProtectedReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedPlansRoute =
  SuperAdminProtectedPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedPaymentsRoute =
  SuperAdminProtectedPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedMaintenanceRoute =
  SuperAdminProtectedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedDashboardRoute =
  SuperAdminProtectedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedCompaniesRoute =
  SuperAdminProtectedCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedBackupRoute =
  SuperAdminProtectedBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const SuperAdminProtectedAuditRoute =
  SuperAdminProtectedAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => SuperAdminProtectedRouteRoute,
  } as any)
const AuthenticatedAppWarehousesRoute =
  AuthenticatedAppWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSuppliersRoute =
  AuthenticatedAppSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppStockRoute = AuthenticatedAppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSalesRoute = AuthenticatedAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppQuotationsRoute =
  AuthenticatedAppQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPurchasesRoute =
  AuthenticatedAppPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPosRoute = AuthenticatedAppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInvoicesRoute =
  AuthenticatedAppInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppExpensesRoute =
  AuthenticatedAppExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCompaniesRoute =
  AuthenticatedAppCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAccountingRoute =
  AuthenticatedAppAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/super-admin': typeof SuperAdminProtectedRouteRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/app/accounting': typeof AuthenticatedAppAccountingRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/companies': typeof AuthenticatedAppCompaniesRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/pos': typeof AuthenticatedAppPosRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/purchases': typeof AuthenticatedAppPurchasesRoute
  '/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/sales': typeof AuthenticatedAppSalesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/stock': typeof AuthenticatedAppStockRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/warehouses': typeof AuthenticatedAppWarehousesRoute
  '/super-admin/audit': typeof SuperAdminProtectedAuditRoute
  '/super-admin/backup': typeof SuperAdminProtectedBackupRoute
  '/super-admin/companies': typeof SuperAdminProtectedCompaniesRoute
  '/super-admin/dashboard': typeof SuperAdminProtectedDashboardRoute
  '/super-admin/maintenance': typeof SuperAdminProtectedMaintenanceRoute
  '/super-admin/payments': typeof SuperAdminProtectedPaymentsRoute
  '/super-admin/plans': typeof SuperAdminProtectedPlansRoute
  '/super-admin/reports': typeof SuperAdminProtectedReportsRoute
  '/super-admin/settings': typeof SuperAdminProtectedSettingsRoute
  '/super-admin/subscriptions': typeof SuperAdminProtectedSubscriptionsRoute
  '/super-admin/trials': typeof SuperAdminProtectedTrialsRoute
  '/super-admin/users': typeof SuperAdminProtectedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/super-admin': typeof SuperAdminProtectedRouteRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/app/accounting': typeof AuthenticatedAppAccountingRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/companies': typeof AuthenticatedAppCompaniesRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/pos': typeof AuthenticatedAppPosRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/purchases': typeof AuthenticatedAppPurchasesRoute
  '/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/sales': typeof AuthenticatedAppSalesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/stock': typeof AuthenticatedAppStockRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/warehouses': typeof AuthenticatedAppWarehousesRoute
  '/super-admin/audit': typeof SuperAdminProtectedAuditRoute
  '/super-admin/backup': typeof SuperAdminProtectedBackupRoute
  '/super-admin/companies': typeof SuperAdminProtectedCompaniesRoute
  '/super-admin/dashboard': typeof SuperAdminProtectedDashboardRoute
  '/super-admin/maintenance': typeof SuperAdminProtectedMaintenanceRoute
  '/super-admin/payments': typeof SuperAdminProtectedPaymentsRoute
  '/super-admin/plans': typeof SuperAdminProtectedPlansRoute
  '/super-admin/reports': typeof SuperAdminProtectedReportsRoute
  '/super-admin/settings': typeof SuperAdminProtectedSettingsRoute
  '/super-admin/subscriptions': typeof SuperAdminProtectedSubscriptionsRoute
  '/super-admin/trials': typeof SuperAdminProtectedTrialsRoute
  '/super-admin/users': typeof SuperAdminProtectedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/super-admin/_protected': typeof SuperAdminProtectedRouteRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/_authenticated/app/accounting': typeof AuthenticatedAppAccountingRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/companies': typeof AuthenticatedAppCompaniesRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/_authenticated/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/pos': typeof AuthenticatedAppPosRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/purchases': typeof AuthenticatedAppPurchasesRoute
  '/_authenticated/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/sales': typeof AuthenticatedAppSalesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/stock': typeof AuthenticatedAppStockRoute
  '/_authenticated/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/warehouses': typeof AuthenticatedAppWarehousesRoute
  '/super-admin/_protected/audit': typeof SuperAdminProtectedAuditRoute
  '/super-admin/_protected/backup': typeof SuperAdminProtectedBackupRoute
  '/super-admin/_protected/companies': typeof SuperAdminProtectedCompaniesRoute
  '/super-admin/_protected/dashboard': typeof SuperAdminProtectedDashboardRoute
  '/super-admin/_protected/maintenance': typeof SuperAdminProtectedMaintenanceRoute
  '/super-admin/_protected/payments': typeof SuperAdminProtectedPaymentsRoute
  '/super-admin/_protected/plans': typeof SuperAdminProtectedPlansRoute
  '/super-admin/_protected/reports': typeof SuperAdminProtectedReportsRoute
  '/super-admin/_protected/settings': typeof SuperAdminProtectedSettingsRoute
  '/super-admin/_protected/subscriptions': typeof SuperAdminProtectedSubscriptionsRoute
  '/super-admin/_protected/trials': typeof SuperAdminProtectedTrialsRoute
  '/super-admin/_protected/users': typeof SuperAdminProtectedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/super-admin'
    | '/super-admin/login'
    | '/app/accounting'
    | '/app/audit'
    | '/app/companies'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/invoices'
    | '/app/notifications'
    | '/app/pos'
    | '/app/products'
    | '/app/purchases'
    | '/app/quotations'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/stock'
    | '/app/suppliers'
    | '/app/team'
    | '/app/warehouses'
    | '/super-admin/audit'
    | '/super-admin/backup'
    | '/super-admin/companies'
    | '/super-admin/dashboard'
    | '/super-admin/maintenance'
    | '/super-admin/payments'
    | '/super-admin/plans'
    | '/super-admin/reports'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/trials'
    | '/super-admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/super-admin'
    | '/super-admin/login'
    | '/app/accounting'
    | '/app/audit'
    | '/app/companies'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/invoices'
    | '/app/notifications'
    | '/app/pos'
    | '/app/products'
    | '/app/purchases'
    | '/app/quotations'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/stock'
    | '/app/suppliers'
    | '/app/team'
    | '/app/warehouses'
    | '/super-admin/audit'
    | '/super-admin/backup'
    | '/super-admin/companies'
    | '/super-admin/dashboard'
    | '/super-admin/maintenance'
    | '/super-admin/payments'
    | '/super-admin/plans'
    | '/super-admin/reports'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/trials'
    | '/super-admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/super-admin/_protected'
    | '/super-admin/login'
    | '/_authenticated/app/accounting'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/companies'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/expenses'
    | '/_authenticated/app/invoices'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/pos'
    | '/_authenticated/app/products'
    | '/_authenticated/app/purchases'
    | '/_authenticated/app/quotations'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/sales'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/stock'
    | '/_authenticated/app/suppliers'
    | '/_authenticated/app/team'
    | '/_authenticated/app/warehouses'
    | '/super-admin/_protected/audit'
    | '/super-admin/_protected/backup'
    | '/super-admin/_protected/companies'
    | '/super-admin/_protected/dashboard'
    | '/super-admin/_protected/maintenance'
    | '/super-admin/_protected/payments'
    | '/super-admin/_protected/plans'
    | '/super-admin/_protected/reports'
    | '/super-admin/_protected/settings'
    | '/super-admin/_protected/subscriptions'
    | '/super-admin/_protected/trials'
    | '/super-admin/_protected/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SuperAdminProtectedRouteRoute: typeof SuperAdminProtectedRouteRouteWithChildren
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/_protected': {
      id: '/super-admin/_protected'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/super-admin/_protected/users': {
      id: '/super-admin/_protected/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminProtectedUsersRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/trials': {
      id: '/super-admin/_protected/trials'
      path: '/trials'
      fullPath: '/super-admin/trials'
      preLoaderRoute: typeof SuperAdminProtectedTrialsRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/subscriptions': {
      id: '/super-admin/_protected/subscriptions'
      path: '/subscriptions'
      fullPath: '/super-admin/subscriptions'
      preLoaderRoute: typeof SuperAdminProtectedSubscriptionsRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/settings': {
      id: '/super-admin/_protected/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminProtectedSettingsRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/reports': {
      id: '/super-admin/_protected/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminProtectedReportsRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/plans': {
      id: '/super-admin/_protected/plans'
      path: '/plans'
      fullPath: '/super-admin/plans'
      preLoaderRoute: typeof SuperAdminProtectedPlansRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/payments': {
      id: '/super-admin/_protected/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminProtectedPaymentsRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/maintenance': {
      id: '/super-admin/_protected/maintenance'
      path: '/maintenance'
      fullPath: '/super-admin/maintenance'
      preLoaderRoute: typeof SuperAdminProtectedMaintenanceRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/dashboard': {
      id: '/super-admin/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminProtectedDashboardRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/companies': {
      id: '/super-admin/_protected/companies'
      path: '/companies'
      fullPath: '/super-admin/companies'
      preLoaderRoute: typeof SuperAdminProtectedCompaniesRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/backup': {
      id: '/super-admin/_protected/backup'
      path: '/backup'
      fullPath: '/super-admin/backup'
      preLoaderRoute: typeof SuperAdminProtectedBackupRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/super-admin/_protected/audit': {
      id: '/super-admin/_protected/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof SuperAdminProtectedAuditRouteImport
      parentRoute: typeof SuperAdminProtectedRouteRoute
    }
    '/_authenticated/app/warehouses': {
      id: '/_authenticated/app/warehouses'
      path: '/warehouses'
      fullPath: '/app/warehouses'
      preLoaderRoute: typeof AuthenticatedAppWarehousesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/suppliers': {
      id: '/_authenticated/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AuthenticatedAppSuppliersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/stock': {
      id: '/_authenticated/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AuthenticatedAppStockRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/sales': {
      id: '/_authenticated/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AuthenticatedAppSalesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/quotations': {
      id: '/_authenticated/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AuthenticatedAppQuotationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/purchases': {
      id: '/_authenticated/app/purchases'
      path: '/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AuthenticatedAppPurchasesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/pos': {
      id: '/_authenticated/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AuthenticatedAppPosRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/invoices': {
      id: '/_authenticated/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AuthenticatedAppInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/expenses': {
      id: '/_authenticated/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AuthenticatedAppExpensesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/companies': {
      id: '/_authenticated/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AuthenticatedAppCompaniesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/accounting': {
      id: '/_authenticated/app/accounting'
      path: '/accounting'
      fullPath: '/app/accounting'
      preLoaderRoute: typeof AuthenticatedAppAccountingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAccountingRoute: typeof AuthenticatedAppAccountingRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppCompaniesRoute: typeof AuthenticatedAppCompaniesRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppExpensesRoute: typeof AuthenticatedAppExpensesRoute
  AuthenticatedAppInvoicesRoute: typeof AuthenticatedAppInvoicesRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppPosRoute: typeof AuthenticatedAppPosRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppPurchasesRoute: typeof AuthenticatedAppPurchasesRoute
  AuthenticatedAppQuotationsRoute: typeof AuthenticatedAppQuotationsRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSalesRoute: typeof AuthenticatedAppSalesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStockRoute: typeof AuthenticatedAppStockRoute
  AuthenticatedAppSuppliersRoute: typeof AuthenticatedAppSuppliersRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppWarehousesRoute: typeof AuthenticatedAppWarehousesRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAccountingRoute: AuthenticatedAppAccountingRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppCompaniesRoute: AuthenticatedAppCompaniesRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppExpensesRoute: AuthenticatedAppExpensesRoute,
  AuthenticatedAppInvoicesRoute: AuthenticatedAppInvoicesRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppPosRoute: AuthenticatedAppPosRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppPurchasesRoute: AuthenticatedAppPurchasesRoute,
  AuthenticatedAppQuotationsRoute: AuthenticatedAppQuotationsRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSalesRoute: AuthenticatedAppSalesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStockRoute: AuthenticatedAppStockRoute,
  AuthenticatedAppSuppliersRoute: AuthenticatedAppSuppliersRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppWarehousesRoute: AuthenticatedAppWarehousesRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SuperAdminProtectedRouteRouteChildren {
  SuperAdminProtectedAuditRoute: typeof SuperAdminProtectedAuditRoute
  SuperAdminProtectedBackupRoute: typeof SuperAdminProtectedBackupRoute
  SuperAdminProtectedCompaniesRoute: typeof SuperAdminProtectedCompaniesRoute
  SuperAdminProtectedDashboardRoute: typeof SuperAdminProtectedDashboardRoute
  SuperAdminProtectedMaintenanceRoute: typeof SuperAdminProtectedMaintenanceRoute
  SuperAdminProtectedPaymentsRoute: typeof SuperAdminProtectedPaymentsRoute
  SuperAdminProtectedPlansRoute: typeof SuperAdminProtectedPlansRoute
  SuperAdminProtectedReportsRoute: typeof SuperAdminProtectedReportsRoute
  SuperAdminProtectedSettingsRoute: typeof SuperAdminProtectedSettingsRoute
  SuperAdminProtectedSubscriptionsRoute: typeof SuperAdminProtectedSubscriptionsRoute
  SuperAdminProtectedTrialsRoute: typeof SuperAdminProtectedTrialsRoute
  SuperAdminProtectedUsersRoute: typeof SuperAdminProtectedUsersRoute
}

const SuperAdminProtectedRouteRouteChildren: SuperAdminProtectedRouteRouteChildren =
  {
    SuperAdminProtectedAuditRoute: SuperAdminProtectedAuditRoute,
    SuperAdminProtectedBackupRoute: SuperAdminProtectedBackupRoute,
    SuperAdminProtectedCompaniesRoute: SuperAdminProtectedCompaniesRoute,
    SuperAdminProtectedDashboardRoute: SuperAdminProtectedDashboardRoute,
    SuperAdminProtectedMaintenanceRoute: SuperAdminProtectedMaintenanceRoute,
    SuperAdminProtectedPaymentsRoute: SuperAdminProtectedPaymentsRoute,
    SuperAdminProtectedPlansRoute: SuperAdminProtectedPlansRoute,
    SuperAdminProtectedReportsRoute: SuperAdminProtectedReportsRoute,
    SuperAdminProtectedSettingsRoute: SuperAdminProtectedSettingsRoute,
    SuperAdminProtectedSubscriptionsRoute:
      SuperAdminProtectedSubscriptionsRoute,
    SuperAdminProtectedTrialsRoute: SuperAdminProtectedTrialsRoute,
    SuperAdminProtectedUsersRoute: SuperAdminProtectedUsersRoute,
  }

const SuperAdminProtectedRouteRouteWithChildren =
  SuperAdminProtectedRouteRoute._addFileChildren(
    SuperAdminProtectedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SuperAdminProtectedRouteRoute: SuperAdminProtectedRouteRouteWithChildren,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
